package chatroom:common;

interface types {

    type room-name = string;
    type user-id = string;
    type message-body = string;

    record room-message {
        room: room-name,
        sender: user-id,
        body: string
    }

}
